name: Test

on:
  push:
  pull_request:
  schedule:
    - cron: '0 12 1 * *'

jobs:
  test:
    strategy:
      matrix:
        svelte:
          [
            svelte@2,
            svelte@3.12,
            svelte@3.15,
            svelte@3.16,
            svelte@3.18,
            svelte@3.21,
            svelte@3.24,
            svelte@3.27,
            svelte@3.30,
            svelte@3.33,
            svelte@3.34,
            svelte@3.35,
            svelte@3.36,
            svelte@3.37,
            svelte@3.38,
            svelte@3.39,
            svelte@3.40,
            svelte@3.41,
            svelte@3.42,
            svelte@3.43,
            svelte@3.44,
            svelte@3.45,
            svelte@3.46,
            svelte@latest,
          ]
        jest: [jest@latest]
        node: [14.x]
        include:
          - svelte: svelte@latest
            jest: jest@latest
            node: 15.x
          - svelte: svelte@latest
            jest: jest@latest
            node: 16.x
          - svelte: svelte@latest
            jest: jest@latest
            node: 17.x
          - svelte: svelte@latest
            jest: jest@25.0.0
            node: 14.x
          - svelte: svelte@latest
            jest: jest@26.0.0
            node: 14.x
          - svelte: svelte@latest
            jest: jest@27.0.0
            node: 14.x
          - svelte: svelte@latest
            jest: jest@28.0.0
            node: 14.x
    env:
      SVELTE_VERSION: ${{ matrix.svelte }}
      JEST_VERSION: ${{ matrix.jest }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm i $SVELTE_VERSION --save-dev && npm i
      - run: npm test
